name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.16
          architecture: x64

      - name: Setup vendor libs
        run: |
          pip install https://github.com/apiad/illiterate/archive/refs/heads/master.zip

      - name: Setup dependencies and build
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
          source $HOME/.poetry/env
          poetry config virtualenvs.create false
          cd autogoal && poetry install
          cd autogoal && poetry build

      - name: Build docs
        run: make docs
        env:
          BUILD_ENVIRONMENT: development

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and Test
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: autogoal/autogoal:test
          context: "."
          file: "tests/tests.dockerfile"

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: autogoal/autogoal.github.io
          publish_branch: master
          publish_dir: ./site
