name: Release Contribs to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.16
          architecture: x64

      - name: Setup dependencies and build
        run: |
          pip install poetry==1.2
          poetry config virtualenvs.create true
          for dir in autogoal_contrib/*; do
            if [ -d "$dir" ]; then
              cd $dir
              poetry install
              poetry build
              cd ../..
            fi
          done

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Publish
        run: |
          for dir in autogoal_contrib/*; do
            if [ -d "$dir" ]; then
              cd $dir
              poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
              cd ../..
            fi
          done

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: autogoal/autogoal.github.io
          publish_branch: master
          publish_dir: ./site
