name: Test Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64

      - name: Setup dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
          source $HOME/.poetry/env
          poetry config virtualenvs.create false
          poetry install --extras dev

      - name: Check format
        run: black --check autogoal/ tests/

      - name: Run core tests
        run: make test-core
        env:
          BUILD_ENVIRONMENT: development 

      - name: Run codecov
        run: python -m codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
